behaviors:
  C123_15cm:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      #memory:
      #  memory_size: 64
      #  sequence_length: 32
    reward_signals:
      extrinsic: 
        gamma: 0.99
        strength: 1.0

    keep_checkpoints: 50
    max_steps: 25%5000000
    time_horizon: 128
    summary_freq: 50000
    threaded: true
environment_parameters:
   curriculumDetect:
       curriculum:
           - name: GrabingCube
             completion_criteria:
               measure: progress
               behavior: C123_15cm
               signal_smoothing: true
               min_lesson_length: 500
               threshold: 1 #2500w
             value: 3
           - name: PlacingCube
             completion_criteria:
               measure: progress
               behavior: C123_15cm
               signal_smoothing: true
               min_lesson_length: 500
               threshold: 1 
             value: 1




           - name: TouchingCube
             completion_criteria:
               measure: progress
               behavior: C123_15cm
               signal_smoothing: true
               min_lesson_length: 500
               threshold: 0 #50w
             value: 2



