behaviors:
  TouchMoveCube:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003 
      learning_rate_schedule: linear
      batch_size: 512             
      buffer_size: 512000
      buffer_init_steps: 5000 
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: true
      hidden_units: 128 
      num_layers: 2  
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
    keep_checkpoints: 50
    max_steps: 10000000  # 一般500~1000w
    time_horizon: 128
    summary_freq: 50000 
environment_parameters:
   curriculumDetect:
       curriculum:
           - name: GrabingCube
             completion_criteria:
               measure: progress
               behavior: TouchMoveCube
               signal_smoothing: true
               min_lesson_length: 500
               threshold: 1 #1500w
             value: 3